name: "Run load tests"
description: "Runs load tests against an API endpoint"
inputs:
   api-endpoint:
     required: true
     description: "The API endpoint to run load tests against"
   output-report-file-name:
     required: true
     description: "The name of the output report"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - run: npm i artillery -g
      shell: bash

    - name: Execute load tests
      shell: bash
      run: artillery run loadtest/load-test.yml --target "${{ inputs.api-endpoint }}"

    # Sleep allows CloudWatch logs to catch up before generating report data
    - name: Sleep for 60 seconds
      shell: bash
      run: sleep 60s

    - name: Create report file
      run: cd ./reports && wget -O ${{ inputs.output-report-file-name }} ${{ inputs.api-endpoint }}test-results
      shell: bash

    - name: Commit report
      shell: bash
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git add --all
        git commit -am "Automated report"
        git push