AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    MemorySize: 1024
    Architectures: ["x86_64"]
    Runtime: dotnetcore3.1
    Timeout: 10
    Tracing: PassThrough
    Environment:
      Variables:
        PRODUCT_TABLE_NAME: !Ref Table
    Layers:
      - arn:aws:lambda:eu-west-1:901920570463:layer:aws-otel-collector-amd64-ver-0-51-0:1
  Api:
    TracingEnabled: True

Resources:
  GetProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./GetProducts/
      Handler: GetProducts::GetProducts.Function::TracingFunctionHandler
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: dynamodb:Scan
              Resource: !GetAtt Table.Arn

  GetProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./GetProduct/
      Handler: GetProduct::GetProduct.Function::TracingFunctionHandler
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{id}
            Method: GET
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: dynamodb:GetItem
              Resource: !GetAtt Table.Arn

  DeleteProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./DeleteProduct/
      Handler: DeleteProduct::DeleteProduct.Function::TracingFunctionHandler
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{id}
            Method: DELETE
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:DeleteItem
                - dynamodb:GetItem
              Resource: !GetAtt Table.Arn

  PutProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./PutProduct/
      Handler: PutProduct::PutProduct.Function::TracingFunctionHandler
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{id}
            Method: PUT
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: dynamodb:PutItem
              Resource: !GetAtt Table.Arn

  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/"