AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    MemorySize: 1024
    Architectures: [!Ref LambdaArchitecture]
    Runtime: dotnetcore3.1
    Timeout: 30
    Tracing: PassThrough
    Environment:
      Variables:
        PRODUCT_TABLE_NAME: !Ref Table
    Layers:
      - !If [!Equals [ !Ref LambdaArchitecture, x86_64 ], arn:aws:lambda:eu-west-1:901920570463:layer:aws-otel-collector-amd64-ver-0-51-0:1, arn:aws:lambda:eu-west-1:901920570463:layer:aws-otel-collector-arm64-ver-0-51-0:1]
  Api:
    TracingEnabled: True

Parameters:
  LambdaArchitecture:
    Type: String
    AllowedValues:
      - arm64
      - x86_64
    Description: Enter arm64 or x86_64

Resources:
  GetProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./GetProducts/
      Handler: GetProducts::GetProducts.Function::TracingFunctionHandler
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: dynamodb:Scan
              Resource: !GetAtt Table.Arn

  GetProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./GetProduct/
      Handler: GetProduct::GetProduct.Function::TracingFunctionHandler
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{id}
            Method: GET
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: dynamodb:GetItem
              Resource: !GetAtt Table.Arn

  DeleteProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./DeleteProduct/
      Handler: DeleteProduct::DeleteProduct.Function::TracingFunctionHandler
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{id}
            Method: DELETE
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:DeleteItem
                - dynamodb:GetItem
              Resource: !GetAtt Table.Arn

  PutProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./PutProduct/
      Handler: PutProduct::PutProduct.Function::TracingFunctionHandler
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{id}
            Method: PUT
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: dynamodb:PutItem
              Resource: !GetAtt Table.Arn

  GenerateLoadTestResults:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./GenerateLoadTestResults/
      Handler: GenerateLoadTestResults::GenerateLoadTestResults.Function::FunctionHandler
      Runtime: dotnet6
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /test-results
            Method: GET
      Environment:
        Variables:
          LOG_GROUP_PREFIX: !Sub "/aws/lambda/net-31-otel-"
          LOAD_TEST_TYPE: "NET 3.1 with OTEL"
          LAMBDA_ARCHITECTURE: !Ref LambdaArchitecture
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Sid: AllowStartQueries
              Effect: Allow
              Action:
                - logs:DescribeLogGroups
                - logs:StartQuery
              Resource: "*"
            - Sid: AllowGetQueryResults
              Effect: Allow
              Action: logs:GetQueryResults
              Resource: "*"

  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/"