name: NET 6

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feat/container-samples
    paths:
      - src/NET6Containers/**
jobs:

  build-deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2  
        - name: Build and Deploy
          uses: ./.github/actions/sam-build-and-deploy
          with:
            aws-access-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}
            dotnet-version: '6.0.x'
            template-file-path: ./src/NET6Containers/template.yaml
            stack-name: net-6-containers
            s3-bucket-name: aws-dotnet-lambda-testing

  load-test-arm:
      needs: build-deploy
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2  
        - name: Run Load Tests
          uses: ./.github/actions/run-load-test
          with:
            api-endpoint: ${{ secrets.API_ENDPOINT_NET_6_CONTAINERS_ARM }}

  load-test-x86:
      needs: build-deploy
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2  
        - name: Run Load Tests
          uses: ./.github/actions/run-load-test
          with:
            api-endpoint: ${{ secrets.API_ENDPOINT_NET_6_CONTAINERS_X86 }}

  generate-report-arm:
      needs: [load-test-arm, load-test-x86]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2  
        - name: Generate reports
          uses: ./.github/actions/generate-report
          with:
            api-endpoint: ${{ secrets.API_ENDPOINT_NET_6_CONTAINERS_ARM }}
            output-report-file-name: net-6-arm-output.md

  generate-report-x86:
      needs: [generate-report-arm]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2  
        - name: Generate reports
          uses: ./.github/actions/generate-report
          with:
            api-endpoint: ${{ secrets.API_ENDPOINT_NET_6_CONTAINERS_X86 }}
            output-report-file-name: net-6-x86-output.md
