name: NET 6

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/NET6/**
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sleep for 10 seconds
        run: sleep 10s
      - uses: actions/setup-python@v2
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

# Build and deploy ARM
      - run: sam build -t ./src/NET6/template.yaml --parameter-overrides LambdaArchitecture=arm64
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name net-6-base-arm64 --s3-prefix net6-arm64 --s3-bucket aws-dotnet-lambda-testing --capabilities CAPABILITY_IAM --parameter-overrides LambdaArchitecture=arm64
      
# Build and deploy x86
      - run: sam build -t ./src/NET6/template.yaml --parameter-overrides LambdaArchitecture=x86_64
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name net-6-base-x86-64 --s3-prefix net6-x86_64 --s3-bucket aws-dotnet-lambda-testing --capabilities CAPABILITY_IAM --parameter-overrides LambdaArchitecture=x86_64

  artillery:
      needs: build-deploy
      runs-on: ubuntu-latest
      container: artilleryio/artillery:latest
      steps:
        - uses: actions/checkout@v2  
        - uses: actions/setup-node@v3
          with:
            node-version: 16

        - run: npm i artillery -g

        - name: Execute load tests
          run: artillery run loadtest/load-test.yml --target "${{ secrets.API_ENDPOINT_NET_6 }}"

        # Sleep allows CloudWatch logs to catch up before generating report data
        - name: Sleep for 60 seconds
          run: sleep 60s

        - name: Create report file
          run: cd ./reports && curl ${{ secrets.API_ENDPOINT_NET_6 }}test-results -o net-6-output.md

        - name: Commit report
          run: |
            git config --global user.name 'GitHub Actions Bot'
            git add --all
            git commit -am "Automated report"
            git push

