on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/NET6/**
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: sam build -t ./src/NET6/template.yaml
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name net-6 --s3-prefix net6 --s3-bucket aws-dotnet-lambda-testing --capabilities CAPABILITY_IAM

  artillery:
      needs: build-deploy
      runs-on: ubuntu-latest
      container: artilleryio/artillery:latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Make reports directory
          run: mkdir reports

        - name: Execute load tests
          run: /home/node/artillery/bin/artillery run loadtest/load-test.yml --target "${{ secrets.API_ENDPOINT_NET_6 }}"

        - name: Generate HTML report
          run: /home/node/artillery/bin/artillery report --output reports/report reports/net-6-report.json

        - name: Archive test report
          uses: actions/upload-artifact@v2
          with:
            name: artillery-test-report
            path: reports/*
